# RUNTIME
FROM python:3.6.3-slim

# VOLUMES
WORKDIR /app
VOLUME /tmp

ADD . /app

# INSTALL DEPENDENCIES
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# SLACK TOKEN
ENV API_TOKEN None

# POSTGRES DETAILS
ENV PGUSER None
ENV PGHOST None
ENV PGPASS None
ENV PGPORT None

# ENTRYPOINT SETTINGS
CMD ["python3", "Athena/run.py"]